# Generated by Django 2.2.11 on 2020-03-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('fuel_type', models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'CNG')])),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
